### ISSUE TITLE
Filter condition should also check determination status

### ISSUE THREAD

**Issue by aepstein** [Bumppoman/corporations-oaths-stamping#1]
https://github.com/Bumppoman/corporations-oaths-stamping/blob/3cad8087fadba986bc9f3e8fd2d8ccedd211f7a5/app.go#L58

The filter only checks whether the file is staged. I think it also needs to check whether it is approved. This would probably be easiest to do if the Submissions lookup column was updated to incorporate the Determination field.

**Comment by Bumppoman** [comment]
So do we think `Filter("StagedforFiling eq null and Filing_x003a_Determination eq 'Accepted'")`?

**Comment by Bumppoman** [comment]
Resolved in fdea2de9191bc49d0f6a71f4882088eeed3f9e24

**Comment by Bumppoman** [comment]
Resolved in fdea2de9191bc49d0f6a71f4882088eeed3f9e24
